# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Noto' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Noto
  
  target 'NotoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Noto-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Noto-tvOS

  target 'Noto-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
